# Project information
site_name: Google ADK(Agent Development Kit ) 中文文档
site_url: https://google-agent-sdk.agentdevhub.com/
site_description: Google ADK(Agent Development Kit ) 是由谷歌开源的 AI 代理框架，专为开发和部署 AI 代理而设计，支持 Gemini 模型和 Google AI 工具的紧密集成，一个开源的、代码优先的Python工具包，用于灵活可控地构建、评估和部署复杂AI智能体。
site_dir: site

# Repository
repo_name: Google-Agent-SDK
repo_url: https://github.com/agentdevhub/Google-Agent-SDK

# Copyright
copyright: Copyright Google 2025

# Custom CSS
extra_css:
  - stylesheets/custom.css

# Configuration
theme:
  name: material
  font:
    text: Google Sans
    code: Roboto Mono
  logo: assets/agent-development-kit.png
  favicon: assets/agent-development-kit.png
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.code.select
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - toc.follow

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

# Plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        'get-started/local-testing.md': 'get-started/testing.md'

# Navigation
nav:
  - 首页: index.md
  - 入门指南:
    - get-started/index.md
    - 安装指南: get-started/installation.md
    - 快速入门: get-started/quickstart.md
    - 快速入门 (streaming): get-started/quickstart-streaming.md
    - 教程: get-started/tutorial.md
    - 测试方法: get-started/testing.md
    - 示例代理: https://github.com/google/adk-samples
    - 关于 ADK: get-started/about.md
  - 代理系统:
    - agents/index.md
    - LLM 代理: agents/llm-agents.md
    - 工作流代理:
      - agents/workflow-agents/index.md
      - 顺序代理: agents/workflow-agents/sequential-agents.md
      - 循环代理: agents/workflow-agents/loop-agents.md
      - 并行代理: agents/workflow-agents/parallel-agents.md
    - 自定义代理: agents/custom-agents.md
    - 多代理系统: agents/multi-agents.md
    - 模型: agents/models.md
  - 工具集:
    - tools/index.md
    - 函数工具: tools/function-tools.md
    - 内置工具: tools/built-in-tools.md
    - 第三方工具: tools/third-party-tools.md
    - Google Cloud 工具: tools/google-cloud-tools.md
    - MCP 工具: tools/mcp-tools.md
    - OpenAPI 工具: tools/openapi-tools.md
    - 身份验证: tools/authentication.md
  - 部署:
    - deploy/index.md
    - Agent Engine: deploy/agent-engine.md
    - Cloud Run: deploy/cloud-run.md
  - 会话与记忆:
    - sessions/index.md
    - 会话: sessions/session.md
    - 状态: sessions/state.md
    - 记忆机制: sessions/memory.md
  - 制品:
    - artifacts/index.md
  - 回调函数:
    - callbacks/index.md
    - 回调类型: callbacks/types-of-callbacks.md
    - 回调模式: callbacks/design-patterns-and-best-practices.md
  - 运行时:
    - runtime/index.md
  - 事件:
    - events/index.md
  - 上下文:
    - context/index.md
  - 评估:
    - evaluate/index.md
  - 指南:
    - 负责任代理指南: guides/responsible-agents.md
  - 贡献指南: contributing-guide.md
  - API 参考: api-reference/index.html